services:

  npm:
    build: .
    container_name: resume-frontend-npm
    #restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/npm/entrypoint.sh:/entrypoint.sh
      #- ./npm_modules:/var/www/node_modules
    ports:
      - "5176:5173"
    extra_hosts:
      - "resume.loc:host-gateway"
    environment:
      - APP_ENV=${APP_ENV:-prod}
    entrypoint: ['/entrypoint.sh']
  #      - NPM_COMMAND=npm run dev -- --host 0.0.0.0
  #    command: "npm run ${NPM_COMMAND:-build}"

  nginx:
    image: nginx:1.29
    container_name: resume-frontend-nginx
    restart: unless-stopped
    ports:
      - "8087:80"
    volumes:
      #- ./dist:/usr/share/nginx/html
      - .docker/nginx/dev.conf:/tmp/dev.conf
      - .docker/nginx/prod.conf:/tmp/prod.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/entrypoint.sh:/entrypoint.sh
    depends_on:
      - npm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ['/entrypoint.sh']
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - NPM_COMMAND=${NPM_COMMAND:-up}

networks:
  default:
    external: true
    name: proxy